name: conectemos
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  device_info: ^0.4.0+4
  share: ^0.6.4+3
  firebase_dynamic_links: ^0.5.3
  firebase_core: "0.5.0"
  cloud_firestore: ^0.14.0+2
  firebase_database: ^4.0.0
  circle_list: ^1.0.2
  flutter_svg: ^0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
    - assets/modos_de_juego.png
    - assets/reglas_con_texto.png
    - assets/icono_entrar.png
    - assets/icono_crear_grupo.png
    - assets/icono_ok_sin_texto.png
    - assets/icono_reglas.png
    - assets/compartir_icono.png
    - assets/icono_pregunto.png
    - assets/icono_pregunto_opaco.png
    - assets/icono_todos.png
    - assets/icono_todos_opaco.png
    - assets/icono_respondo.png
    - assets/icono_respondo_opaco.png
    - assets/icono_tus_cartas_opaco.png
    - assets/icono_tus_cartas.png
    - assets/disco_central_para_texto2.png
    - assets/disco_central_para_todos.png
    - assets/disco_central_para_uno.png
    - assets/barra_nombre.png
    - assets/barra_jugador_amarillo.png
    - assets/barra_jugador_azul.png
    - assets/barra_jugador_calipso.png
    - assets/barra_jugador_morado.png
    - assets/barra_jugador_naranjo.png
    - assets/barra_jugador_negro.png
    - assets/barra_jugador_pistacho.png
    - assets/barra_jugador_rojo.png
    - assets/barra_jugador_rosado.png
    - assets/barra_jugador_verde_musgo.png
    - assets/barra_jugador_verde.png
    - assets/barra_jugador_violeta.png
    - assets/barra_con_color_todos_responden.png
    - assets/jugador_amarillo.png
    - assets/jugador_amarillo_con_circulo.png
    - assets/jugador_azul.png
    - assets/jugador_azul_con_circulo.png
    - assets/jugador_calipso.png
    - assets/jugador_calipso_con_circulo.png
    - assets/jugador_naranjo.png
    - assets/jugador_naranjo_con_circulo.png
    - assets/jugador_negro.png
    - assets/jugador_negro_con_circulo.png
    - assets/jugador_pistacho.png
    - assets/jugador_pistacho_con_circulo.png
    - assets/jugador_rojo.png
    - assets/jugador_rojo_con_circulo.png
    - assets/jugador_rosado.png
    - assets/jugador_rosado_con_circulo.png
    - assets/jugador_verde_musgo.png
    - assets/jugador_verde_musgo_con_circulo.png
    - assets/jugador_verde.png
    - assets/jugador_verde_con_circulo.png
    - assets/jugador_violeta.png
    - assets/jugador_violeta_con_circulo.png
    - assets/jugador_morado.png
    - assets/jugador_morado_con_circulo.png
    - assets/protruding_squares.svg
    - assets/fondo3.svg
    - assets/fondo1.svg
    - assets/circulo_preguntas.png
    - assets/icono_ok.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
